line-length = 120

target-version = "py311"

[lint]
extend-select = [
    "E501",  # Line length
    "I"      # isort - sort imports
]

[lint.pycodestyle]
max-line-length = 120

[format]
line-ending = "lf"
